In [278]:
#= 
net = Chain(
    Conv((3, 3), 1 => 6,  relu),
    MaxPool((2, 2)),
    Conv((3, 3), 6 => 16, relu),
    MaxPool((2, 2)),
    Flux.flatten,
    Dense(400 => 84, relu), 
    Dense(84 => 10, identity),
)
=#

In [279]:
x = randn(26,26,6)

26×26×6 Array{Float64, 3}:
[:, :, 1] =
  0.53199     0.167464    1.09982   …   0.186573   -0.335856    1.90961
 -1.34059    -0.542263   -0.456596      0.463551    1.00267    -1.33318
  1.036      -0.71242     0.581237      0.773011    1.41672     1.45154
 -0.918312    1.19826     1.54701      -0.560073    2.49749     0.322769
  2.00953     0.426619    1.13572       1.45645    -0.925628   -0.168236
 -0.648224    0.958443   -2.25662   …  -0.814161   -0.303327   -0.864292
 -0.143426   -0.283337    0.957346      0.75426     0.865937    2.17279
  1.12966    -0.0171666  -0.174617      1.3438     -0.642333    1.3554
  0.3992     -0.359256   -0.280269     -0.907977   -0.519802   -1.14069
  1.30973     0.245123    1.1523       -0.256025   -0.527601    1.40794
  ⋮                                 ⋱                           ⋮
 -0.0744645   0.40542    -0.185304      1.80539     0.2708     -0.309335
 -1.89304     0.0735529   0.196998     -0.323921    1.06285     0.271666
  1.28443     1.63735     0

In [280]:
function maxpool(x)
    input_height, input_width, layers = size(x)

    output_height = div(input_height, 2)
    output_width = div(input_width, 2)

    y = zeros(output_height, output_width, layers)
    for c in 1:layers
        for j in 1:output_height
            for i in 1:output_width
                region = x[2*j - 1:2*j, 2*i - 1:i *2, c]
                y[j, i, c] = maximum(region)
            end
        end
    end
    
    return y
end

maxpool (generic function with 1 method)

In [281]:
function maxpool2(x)
    input_height, input_width, layers = size(x)

    output_height = div(input_height, 2)
    output_width = div(input_width, 2)

    y = zeros(output_height, output_width, layers)
    for i in 1:output_width
        
        for j in 1:output_height
            for c in 1:layers
            
                
                region = x[2*j - 1:2*j, 2*i - 1:i *2, c]
                y[j, i, c] = maximum(region)
            end
        end
    end
    
    return y
end

maxpool2 (generic function with 1 method)

In [282]:
@btime maxpool(x)
@btime maxpool2(x)
@btime maxpool(x)
@btime maxpool2(x)

  28.900 μs (1015 allocations: 103.12 KiB)
  29.400 μs (1015 allocations: 103.12 KiB)
  28.600 μs (1015 allocations: 103.12 KiB)
  29.100 μs (1015 allocations: 103.12 KiB)


13×13×6 Array{Float64, 3}:
[:, :, 1] =
 0.53199   1.09982    2.17944    …   0.608281   0.463551    1.90961
 1.19826   1.54701    1.8931         0.468603   0.8         2.49749
 2.00953   1.27485    1.29043        1.67021    1.45645    -0.168236
 1.12966   1.78138    0.283914       0.254967   1.58375     2.17279
 1.30973   1.1523     0.841676       0.374699   1.19073     1.40794
 0.677937  1.06364    1.2562     …   0.969623   2.26771     0.759575
 0.827239  2.98616    1.64303        1.0552     2.32984     0.335191
 0.695054  0.763529   1.42601        1.8363     0.442849    0.129578
 0.40542   1.62633    1.28093       -0.226214   1.80868     0.769127
 1.63735   0.800074  -0.192745       1.25456    1.3857      1.06285
 1.27459   0.79333    1.5778     …   0.467047  -0.0510208   1.52999
 1.12523   2.07202    0.832521      -0.125958   1.41608     0.730229
 1.10133   1.85229   -0.0336821      1.02266    0.76776     1.70377

[:, :, 2] =
  1.25439     1.02697     1.01981   …   0.538636    1.8618

In [1]:
using BenchmarkTools

In [43]:
x = randn(26,26,6)

26×26×6 Array{Float64, 3}:
[:, :, 1] =
  0.27513    0.156065    0.698927   …   0.834965   -1.69696     0.0172511
  0.960272   0.135471    1.02201       -1.31116     0.287235    0.608445
  0.186427   0.881904   -0.147124       1.45679    -0.0388663   1.81705
 -0.489905  -0.409384   -0.469153       0.538293    1.55194    -0.601349
  0.41182    1.693       0.0185486      0.497453    0.82336     0.943967
 -0.831087  -2.08335    -1.51408    …   0.0993639   0.649402   -0.677629
  1.11671   -0.0458701  -0.361457       1.64606     0.587923    0.213551
  0.768814  -0.789073    1.10479       -0.771642   -1.86435     0.337765
  0.204408   0.828806    0.13491       -0.141875   -1.80685     0.285319
 -0.976735   0.798469    0.211915       1.08214    -0.0938333   2.59002
  ⋮                                 ⋱                           ⋮
  0.783539  -1.20983     0.408914       0.933       0.418663   -0.494257
  1.21529    0.392411    0.0636395     -1.10843     1.1062     -0.257354
  1.02556   -1.69446

In [45]:
@time y = zeros(size(x))

  0.000021 seconds (3 allocations: 31.781 KiB)


26×26×6 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ⋮                        ⋮              ⋱       ⋮                        ⋮
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0

In [62]:
x = randn(28,28,1,1)
w = randn(3,3,1,6)
g = randn(26,26,6,1)

26×26×6×1 Array{Float64, 4}:
[:, :, 1, 1] =
  0.297237   -0.674639    0.155635    …  -0.927934   -0.550392    0.998193
  0.452485   -0.643298   -0.126499        2.69672     0.849317   -0.0760824
  0.28518     0.0348972   0.479528        1.3956      0.470798    1.33066
 -0.383942    0.566899    0.37222         0.121148    1.1934      0.708541
 -0.562114    0.138233   -1.26525        -0.512695    0.941443   -0.349714
  0.205233   -1.44552    -0.864152    …   0.273816    1.426      -0.670134
  1.19731     0.724182   -0.593826        1.00568    -1.2423      0.0985012
 -0.408545    3.22028    -1.11881        -1.88676    -0.0639473   0.124426
 -0.525721   -0.548058   -0.456622       -0.0188079   0.508401   -0.517411
  0.923667   -0.390999   -1.253          -0.108301   -1.90043     0.137996
  ⋮                                   ⋱                           ⋮
  0.697262   -0.0308085  -0.450164       -1.35652    -0.436743    0.239105
 -1.21398    -0.0365585   0.715137        0.81785    -0.496735