In [15]:
include("load_data.jl")
include("network.jl")
include("layers.jl")

# Preparing train data
x_train = reshape(train_data.features, 28, 28, 1, :)
y_train  = onehotmatrix(train_data.targets, 0:9)

# Preparing test data
x_test = reshape(test_data.features, 28, 28, 1, :) 
y_test = onehotmatrix(test_data.targets, 0:9)

# Learning parameters
settings = (;
eta = 0.01,
epochs = 3,
batchsize = 100,
)


(eta = 0.01, epochs = 3, batchsize = 100)

In [2]:
# Build first model

layers = [
    ConvLayer(3,3,1,6),
    ReLULayer(),
    MaxPoolLayer(),
    FlattenLayer(),
    DenseLayer(84,1014),
    ReLULayer(),
    DenseLayer(10,84),
    LogitCrossEntropyLayer()
];

model = build_graph(layers, (28,28,1),(10));

In [3]:
# Training phase
train_model(model, x_train, y_train', settings)

 48.362671 seconds (269.52 M allocations: 62.392 GiB, 7.04% gc time, 9.75% compilation time)
Epoch:1
Train accuracy: 0.8719
Epoch loss: 1.1240583357808964

 41.843507 seconds (262.75 M allocations: 61.947 GiB, 7.11% gc time)
Epoch:2
Train accuracy: 0.8999666666666667
Epoch loss: 0.3924528280066381

 45.612041 seconds (262.75 M allocations: 61.947 GiB, 6.83% gc time)
Epoch:3
Train accuracy: 0.9122666666666667
Epoch loss: 0.3244783512403392



In [3]:
# Testing phase
test_model(model, x_test, y_test')      

  4.100399 seconds (24.05 M allocations: 2.541 GiB, 6.46% gc time, 44.33% compilation time)
Test Accuracy: 0.0912


In [12]:
w = randn(84,400)
x = randn(400)
w *x

84-element Vector{Float64}:
  18.086119454655872
  -0.6189352319051379
 -40.73979851763418
  15.50589266035927
  -6.985459735637852
   7.785841913197765
 -24.04901780542432
   0.29103894479969483
 -14.751658156452459
  -7.838534432033836
   ⋮
 -11.37991022755799
 -17.64915673030401
   8.73185714308596
   4.140025986456891
  13.186047753851081
  10.989222917745069
 -23.281163371622604
  27.93565526923129
 -22.619460070616714

In [13]:

w*x .+ 0

84-element Vector{Float64}:
  18.086119454655872
  -0.6189352319051379
 -40.73979851763418
  15.50589266035927
  -6.985459735637852
   7.785841913197765
 -24.04901780542432
   0.29103894479969483
 -14.751658156452459
  -7.838534432033836
   ⋮
 -11.37991022755799
 -17.64915673030401
   8.73185714308596
   4.140025986456891
  13.186047753851081
  10.989222917745069
 -23.281163371622604
  27.93565526923129
 -22.619460070616714

In [16]:
# Build second model

layers2 = [
    ConvLayer(3,3,1,6),
    ReLULayer(),
    MaxPoolLayer(),
    ConvLayer(3,3,6,16),
    ReLULayer(),
    MaxPoolLayer(),
    FlattenLayer(),
    DenseLayer(84,400; bias = true),
    ReLULayer(),
    DenseLayer(10,84; bias = true),
    LogitCrossEntropyLayer()
];

model2 = build_graph(layers2, (28,28,1),(10));

In [17]:
# Training phase
train_model(model2, x_train, y_train', settings)

In [10]:
model2.graph

19-element Vector{GraphNode}:
 const [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0;;;]
 var ?
 ┣━ ^ 3×3×1×6 Array{Float64, 4}
 ┗━ ∇ Nothing
 op.?(typeof(convolution))
 op.?(typeof(relu))
 op.?(typeof(maxpool))
 var ?
 ┣━ ^ 3×3×6×16 Array{Float64, 4}
 ┗━ ∇ Nothing
 op.?(typeof(convolution))
 op.?(typeof(relu))
 op.?(typeof(maxpool))
 op.?(typeof(flatten))
 var ?
 ┣━ ^ 84×400 Matrix{Float64}
 ┗━ ∇ Nothing
 var ?
 ┣━ ^ 84×1 Matrix{Float64}
 ┗━ ∇ Nothing
 op.?(typeof(dense))
 op.?(typeof(relu))
 var ?
 ┣━ ^ 10×84 Matrix{Float64}
 ┗━ ∇ Nothing
 var ?
 ┣━ ^ 10×1 Matrix{Float64}
 ┗━ ∇ Nothing
 op.?(typeof(dense))
 const [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
 op.?(typeof(cross_entropy_loss))

In [6]:
# Testing phase
test_model(model2, x_test, y_test')    

  5.811868 seconds (32.12 M allocations: 3.439 GiB, 4.71% gc time, 18.98% compilation time)
Test Accuracy: 0.0
