In [1]:
include("load_data.jl")
include("network.jl")

# Preparing train data
x_train = reshape(train_data.features, 28, 28, 1, :)
y_train  = onehotmatrix(train_data.targets, 0:9)

# Preparing test data
x_test = reshape(test_data.features, 28, 28, 1, :) 
y_test = onehotmatrix(test_data.targets, 0:9)

# Learning parameters
settings = (;
eta = 0.01,
epochs = 3,
batchsize = 100,
)


(eta = 0.01, epochs = 3, batchsize = 100)

In [2]:
# Initializing model
model = initialize_model()

ModelCNN{typeof(dense)}(GraphNode[const [0.44166039423063475 0.21784657089298687 … 0.6259337699736741 0.7622666632384938; 0.7613090668722048 0.5546364974416043 … 0.24419609116885355 0.9610391017086882; … ; 0.40908688659287273 0.155700348221112 … 0.9002249070149322 0.7253291434334481; 0.9878612561986507 0.533237613005764 … 0.9975449711177842 0.6266181865897184;;;], var ?
 ┣━ ^ 3×3×1×6 Array{Float64, 4}
 ┗━ ∇ Nothing, op.?(typeof(convolution)), op.?(typeof(relu)), op.?(typeof(maxpool)), op.?(typeof(flatten)), var wh
 ┣━ ^ 84×1014 Matrix{Float64}
 ┗━ ∇ Nothing, op.?(typeof(dense)), op.?(typeof(relu)), var wo
 ┣━ ^ 10×84 Matrix{Float64}
 ┗━ ∇ Nothing, op.?(typeof(dense)), const [0.02088617078314825, 0.6064156255625909, 0.6701015455246063, 0.6777873214925951, 0.800351186488371, 0.13868633846666856, 0.7512330430239741, 0.06230973576488097, 0.6299390204789411, 0.9022074353219508], op.?(typeof(cross_entropy_loss))], const [0.44166039423063475 0.21784657089298687 … 0.6259337699736741 0.76226666

In [3]:
# Training phase
train_model(model, x_train, y_train', settings)

 44.804579 seconds (268.89 M allocations: 61.986 GiB, 7.93% gc time, 10.43% compilation time)
Epoch:1
Train accuracy: 0.65425
Epoch loss: 15.446189218468923

 36.574034 seconds (262.81 M allocations: 61.585 GiB, 7.09% gc time)
Epoch:2
Train accuracy: 0.8573833333333334
Epoch loss: 6.92130218928597

 30.123141 seconds (262.81 M allocations: 61.585 GiB, 5.14% gc time)
Epoch:3
Train accuracy: 0.8845833333333334
Epoch loss: 4.561009138600506

111.651205 seconds (794.61 M allocations: 185.162 GiB, 6.89% gc time, 4.31% compilation time)


In [4]:
# Testing phase
test_model(model, x_test, y_test')


  1.907697 seconds (20.92 M allocations: 2.333 GiB, 7.42% gc time)
Test Accuracy: 0.8912


In [18]:
import LinearAlgebra: mul!
using BenchmarkTools

x = uniform_rand(26,26,6)

26×26×6 Array{Float64, 3}:
[:, :, 1] =
  0.00250024   0.034355    -0.01399     …   0.00723316    0.0145525
 -0.0326762   -0.0243416   -0.00105213     -0.0296317     0.0165554
  0.0103678   -0.0240043    0.0184108       0.0365294     0.0238482
  0.0387079   -0.0339608    0.0148752      -0.0277479    -0.0417139
 -0.0308651    0.0276818   -0.0122934      -0.000638358  -0.00775789
 -0.0256308    0.00731803   0.0407011   …   0.0204844    -0.0342713
 -0.0176386   -0.016704     0.0366135       0.0132013    -0.0127162
 -0.0322723    0.0305004    0.00246673     -0.00570162    0.0337168
  0.00110595  -0.032833     0.0243318       0.0359983    -0.0291703
 -0.0373406   -0.00693425   0.0246264      -0.032781      0.0196824
  ⋮                                     ⋱                 ⋮
  0.00627598   0.00621121   0.0171441       0.0205451    -0.0194284
 -0.0319193    0.0340821    0.0216996       0.0249341     0.0294821
  0.0141872    0.025685     0.0418022      -0.0131147    -0.0204797
 -0.0291453   -0

In [21]:
@btime (x .> 0) .* x
@btime max.(x, zero(x))

  2.389 μs (4 allocations: 31.81 KiB)
  3.743 μs (5 allocations: 63.53 KiB)


26×26×6 Array{Float64, 3}:
[:, :, 1] =
 0.00250024  0.034355    0.0         …  0.0         0.00723316  0.0145525
 0.0         0.0         0.0            0.0273289   0.0         0.0165554
 0.0103678   0.0         0.0184108      0.0         0.0365294   0.0238482
 0.0387079   0.0         0.0148752      0.0         0.0         0.0
 0.0         0.0276818   0.0            0.0237305   0.0         0.0
 0.0         0.00731803  0.0407011   …  0.020116    0.0204844   0.0
 0.0         0.0         0.0366135      0.0         0.0132013   0.0
 0.0         0.0305004   0.00246673     0.0084708   0.0         0.0337168
 0.00110595  0.0         0.0243318      0.0         0.0359983   0.0
 0.0         0.0         0.0246264      0.00980497  0.0         0.0196824
 ⋮                                   ⋱                          ⋮
 0.00627598  0.00621121  0.0171441      0.00188703  0.0205451   0.0
 0.0         0.0340821   0.0216996      0.0355189   0.0249341   0.0294821
 0.0141872   0.025685    0.0418022      0.0

In [20]:
(x .> 0) .*x

26×26×6 Array{Float64, 3}:
[:, :, 1] =
  0.00250024   0.034355    -0.0         …   0.00723316   0.0145525
 -0.0         -0.0         -0.0            -0.0          0.0165554
  0.0103678   -0.0          0.0184108       0.0365294    0.0238482
  0.0387079   -0.0          0.0148752      -0.0         -0.0
 -0.0          0.0276818   -0.0            -0.0         -0.0
 -0.0          0.00731803   0.0407011   …   0.0204844   -0.0
 -0.0         -0.0          0.0366135       0.0132013   -0.0
 -0.0          0.0305004    0.00246673     -0.0          0.0337168
  0.00110595  -0.0          0.0243318       0.0359983   -0.0
 -0.0         -0.0          0.0246264      -0.0          0.0196824
  ⋮                                     ⋱                ⋮
  0.00627598   0.00621121   0.0171441       0.0205451   -0.0
 -0.0          0.0340821    0.0216996       0.0249341    0.0294821
  0.0141872    0.025685     0.0418022      -0.0         -0.0
 -0.0         -0.0         -0.0         …   0.0185606    0.00939771
 -0.0