In [2]:
include("load_data.jl")
include("network.jl")
include("layers.jl")

# Preparing train data
x_train = reshape(train_data.features, 28, 28, 1, :)
y_train  = onehotmatrix(train_data.targets, 0:9)

# Preparing test data
x_test = reshape(test_data.features, 28, 28, 1, :) 
y_test = onehotmatrix(test_data.targets, 0:9)

# Learning parameters
settings = (;
eta = 0.01,
epochs = 3,
batchsize = 100,
)


(eta = 0.01, epochs = 3, batchsize = 100)

In [2]:
# Build first model

layers = [
    ConvLayer(3,3,1,6),
    ReLULayer(),
    MaxPoolLayer((2,2)),
    FlattenLayer(),
    DenseLayer(84,1014),
    ReLULayer(),
    DenseLayer(10,84),
    LogitCrossEntropyLayer()
];

model = build_graph(layers, (28,28,1),(10));

In [7]:
model.graph

14-element Vector{GraphNode}:
 const [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0;;;]
 var ?
 ┣━ ^ 3×3×1×6 Array{Float64, 4}
 ┗━ ∇ Nothing
 op.?(typeof(convolution))
 op.?(typeof(relu))
 const (2, 2)
 op.?(typeof(maxpool))
 op.?(typeof(flatten))
 var ?
 ┣━ ^ 84×1014 Matrix{Float64}
 ┗━ ∇ 84×1014 Matrix{Float64}
 op.?(typeof(dense))
 op.?(typeof(relu))
 var ?
 ┣━ ^ 10×84 Matrix{Float64}
 ┗━ ∇ 10×84 Matrix{Float64}
 op.?(typeof(dense))
 const [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
 op.?(typeof(cross_entropy_loss))

In [4]:
# Training phase
train_model(model, x_train, y_train', settings)

 46.279454 seconds (267.75 M allocations: 62.238 GiB, 6.95% gc time, 6.47% compilation time)
Epoch:1
Train accuracy: 0.85375
Epoch loss: 1.343389721922229

 42.177763 seconds (263.83 M allocations: 61.982 GiB, 7.16% gc time)
Epoch:2
Train accuracy: 0.8937666666666667
Epoch loss: 0.4223870783628048

 39.291570 seconds (263.83 M allocations: 61.982 GiB, 6.50% gc time)
Epoch:3
Train accuracy: 0.90745
Epoch loss: 0.33583477317819677



In [5]:
# Testing phase
test_model(model, x_test, y_test')      

  1.792528 seconds (20.96 M allocations: 2.335 GiB, 8.64% gc time)
Test Accuracy: 0.9174


In [12]:
w = randn(84,400)
x = randn(400)
w *x

84-element Vector{Float64}:
  18.086119454655872
  -0.6189352319051379
 -40.73979851763418
  15.50589266035927
  -6.985459735637852
   7.785841913197765
 -24.04901780542432
   0.29103894479969483
 -14.751658156452459
  -7.838534432033836
   ⋮
 -11.37991022755799
 -17.64915673030401
   8.73185714308596
   4.140025986456891
  13.186047753851081
  10.989222917745069
 -23.281163371622604
  27.93565526923129
 -22.619460070616714

In [13]:
w*x .+ 0

84-element Vector{Float64}:
  18.086119454655872
  -0.6189352319051379
 -40.73979851763418
  15.50589266035927
  -6.985459735637852
   7.785841913197765
 -24.04901780542432
   0.29103894479969483
 -14.751658156452459
  -7.838534432033836
   ⋮
 -11.37991022755799
 -17.64915673030401
   8.73185714308596
   4.140025986456891
  13.186047753851081
  10.989222917745069
 -23.281163371622604
  27.93565526923129
 -22.619460070616714

In [2]:
# Build second model

layers2 = [
    ConvLayer(3,3,1,6),
    ReLULayer(),
    MaxPoolLayer((2,2)),
    ConvLayer(3,3,6,16),
    ReLULayer(),;alllaaaflllaafsafafffagggsdgdsdg
    MaxPoolLayer((2,2)),
    FlattenLayer(),
    DenseLayer(84,400),
    ReLULayer(),
    DenseLayer(10,84),
    LogitCrossEntropyLayer()
];

model2 = build_graph(layers2, (28,28,1),(10));

In [19]:
# Training phase
train_model(model2, x_train, y_train', settings)

 65.223275 seconds (374.16 M allocations: 47.884 GiB, 4.21% gc time, 5.10% compilation time)
Epoch:1
Train accuracy: 0.8626666666666667
Epoch loss: 1.1311945264238432

 61.194970 seconds (369.92 M allocations: 47.606 GiB, 4.16% gc time)
Epoch:2
Train accuracy: 0.91175
Epoch loss: 0.334613077958039

 63.676855 seconds (369.92 M allocations: 47.606 GiB, 4.05% gc time)
Epoch:3
Train accuracy: 0.9315666666666667
Epoch loss: 0.24359271596375992



In [3]:
# Testing phase
test_model(model2, x_test, y_test')    

  6.981885 seconds (34.66 M allocations: 3.601 GiB, 4.68% gc time, 38.81% compilation time)
Test Accuracy: 0.0


In [6]:
layers3 = [
    ConvLayer(2,2,1,4),
    ReLULayer(),
    MaxPoolLayer((3,3)),
    FlattenLayer(),
    DenseLayer(10,324),
    LogitCrossEntropyLayer()
]

model3 = build_graph(layers3, (28,28,1),(10));

In [8]:
# Training phase
train_model(model3, x_train, y_train', settings)

 18.437443 seconds (98.32 M allocations: 12.630 GiB, 6.18% gc time, 15.80% compilation time)
Epoch:1
Train accuracy: 0.7704666666666666
Epoch loss: 1.7798253142764084

 15.384875 seconds (94.63 M allocations: 12.389 GiB, 7.09% gc time)
Epoch:2
Train accuracy: 0.8310666666666666
Epoch loss: 0.8228385514795735

 15.224846 seconds (94.63 M allocations: 12.389 GiB, 7.28% gc time)
Epoch:3
Train accuracy: 0.8541166666666666
Epoch loss: 0.5689068758250293



In [9]:
# Testing phase
test_model(model3, x_test, y_test')    

  0.941173 seconds (7.03 M allocations: 1.072 GiB, 15.47% gc time)
Test Accuracy: 0.8642
