In [41]:
include("forward_pass.jl")
include("backward_pass.jl");
include("utils.jl");
include("convolution.jl");
include("graph_building.jl");
include("load_data.jl");
#include("scalar_operators.jl");
include("broadcasted_operators.jl")
include("network.jl")


build_graph (generic function with 1 method)

In [43]:
model = build_graph()

13-element Vector{Any}:
 const Float32[0.04520139 0.049940147 … 0.007481339 0.01427927; -0.006278443 0.0028910625 … 0.037539348 -0.058796678; … ; -0.0029164518 -0.022805674 … 0.0136820655 0.034655653; 0.054893784 -0.056367997 … -0.027863318 -0.049806032;;;;]
 var wh1
 ┣━ ^ 3×3×1×6 Array{Float32, 4}
 ┗━ ∇ Nothing
 op.?(typeof(conv))
 op.x1(typeof(relu))
 op.x2(typeof(maxpool))
 op.x3(typeof(flatten))
 var wh2
 ┣━ ^ 1014×84 Matrix{Float64}
 ┗━ ∇ Nothing
 op.?(typeof(mul!))
 op.x4(typeof(relu))
 var wo
 ┣━ ^ 84×10 Matrix{Float64}
 ┗━ ∇ Nothing
 op.x5(typeof(mul!))
 const [-1.5205723269119586 2.2381976183799996 … 1.6278665051866277 0.5431373031589004]
 op.x6(typeof(cross_entropy_loss))

In [42]:
x_train = reshape(train_data.features, 28, 28, 1, :) # insert trivial channel dim
y_train  = onehotmatrix(train_data.targets, 0:9)

x_test = reshape(train_data.features, 28, 28, 1, :) # insert trivial channel dim
y_test = onehotmatrix(train_data.targets, 0:9)

settings = (;
eta = 1e-2,
epochs = 3,
batchsize = 100,
)

(eta = 0.01, epochs = 3, batchsize = 100)

In [45]:
test_model(model, x_test, y_test)

ACCURACY: 0.7901


In [46]:
train_model(model, x_train, y_train, settings.batchsize, settings.eta)

In [51]:
model[12].output

1×10 Matrix{Float64}:
 0.650324  -2.27504  0.497717  0.540688  …  -0.637791  0.0635059  -0.509635

In [37]:
model[5].output


13×13×6 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0      0.0      0.0       0.0      …  0.0      0.0      0.0
 0.0  0.0      0.0      0.0       0.0         0.0      0.0      0.400781
 0.0  0.0      0.0      0.0       0.0         0.0      2.73008  1.06823
 0.0  0.0      0.0      0.0       0.0         6.48285  6.7889   0.0747652
 0.0  0.0      0.0      0.0       0.0         6.91109  2.68549  0.0
 0.0  0.0      0.0      0.0       0.0      …  3.11326  0.0      0.0
 0.0  0.0      0.0      0.0       0.0         0.0      0.0      0.0
 0.0  0.0      0.0      0.0       0.0         0.0      0.0      0.0
 0.0  0.0      0.0      0.236104  5.75725     0.0      0.0      0.0
 0.0  0.0      3.72872  7.28342   6.79023     0.0      0.0      0.0
 0.0  2.98499  6.00027  6.08981   1.52597  …  0.0      0.0      0.0
 0.0  1.47151  2.74224  2.04462   0.0         0.0      0.0      0.0
 0.0  0.0      0.0      0.0       0.0         0.0      0.0      0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0       0.0       …  0.0       

In [64]:
model[3].inputs = (Constant(x), model[3].inputs[2])

op.?(typeof(conv))

In [74]:
max(model[11].output...)

56.93963424859507

In [70]:
model[13].inputs[2]

const [0 1 … 0 0]

In [69]:
model[13].output

2.464584092368422e-12

In [12]:
model[10].gradient

84×10 Matrix{Float64}:
 1.62837e-25  9.08284e-16  4.20881e-20  2.86407  …  2.10447e-16  1.2342e-9
 2.44848e-25  1.36573e-15  6.32851e-20  4.30651     3.16436e-16  1.85579e-9
 0.0          0.0          0.0          0.0         0.0          0.0
 0.0          0.0          0.0          0.0         0.0          0.0
 9.32501e-26  5.20136e-16  2.41021e-20  1.64013     1.20514e-16  7.06776e-10
 0.0          0.0          0.0          0.0      …  0.0          0.0
 1.97833e-25  1.10349e-15  5.11334e-20  3.4796      2.55675e-16  1.49945e-9
 1.3894e-25   7.74986e-16  3.59113e-20  2.44375     1.79563e-16  1.05307e-9
 0.0          0.0          0.0          0.0         0.0          0.0
 1.75564e-25  9.79273e-16  4.53776e-20  3.08792     2.26895e-16  1.33066e-9
 ⋮                                               ⋱               
 0.0          0.0          0.0          0.0      …  0.0          0.0
 0.0          0.0          0.0          0.0         0.0          0.0
 0.0          0.0          0.0          0

In [42]:
x = x4dim[:,:,:,11]

28×28×1 Array{Float32, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0       0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0       0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0       0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0       0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0       0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0       0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0       0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0       0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.027451  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.458824  0.0  0.0  0.0  0.0
 ⋮                        ⋮                   ⋱                 ⋮         
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0       0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.