In [204]:
include("forward_pass.jl")
include("backward_pass.jl");
include("utils.jl");
include("convolution.jl");
include("graph_building.jl");
include("load_data.jl");
#include("scalar_operators.jl");
include("broadcasted_operators.jl")
include("network.jl")

build_graph (generic function with 1 method)

In [205]:
model = build_graph()

(28, 28, 1, 1)(3, 3, 1, 6)(1014, 84)(84, 10)(1, 10)

13-element Vector{Any}:
 const Float32[-0.03851054 -0.03925952 … 0.032242406 -0.008174222; -0.002017099 -0.050906677 … -0.0311617 -0.057012837; … ; 0.0069149295 -0.0066874437 … -0.031533528 0.02412144; 0.023680177 0.03649727 … 0.021443563 0.01507725;;;;]
 var wh1
 ┣━ ^ 3×3×1×6 Array{Float32, 4}
 ┗━ ∇ Nothing
 op.?(typeof(conv))
 op.x1(typeof(relu))
 op.x2(typeof(maxpool))
 op.x3(typeof(flatten))
 var wh2
 ┣━ ^ 1014×84 Matrix{Float64}
 ┗━ ∇ Nothing
 op.?(typeof(mul!))
 op.x4(typeof(relu))
 var wo
 ┣━ ^ 84×10 Matrix{Float64}
 ┗━ ∇ Nothing
 op.x5(typeof(mul!))
 const [0.7273174152263877 0.22433732862193037 … -0.7146577535950686 2.350813734198045]
 op.x6(typeof(cross_entropy_loss))

In [206]:
x4dim = reshape(train_data.features, 28, 28, 1, :) # insert trivial channel dim
yhot  = onehotmatrix(train_data.targets, 0:9)
settings = (;
eta = 1e-2,
epochs = 3,
batchsize = 100,
)

(eta = 0.01, epochs = 3, batchsize = 100)

In [207]:
train_model(model, x4dim, yhot, settings.batchsize, settings.eta)

In [103]:
net, x, y = build_graph();


(28, 28, 1, 1)(3, 3, 1, 6)(1014, 84)(84, 10)(1, 10)

In [196]:
forward!(model)

-8.225988148753503

In [ ]:
backward!(model)

12345678910

In [217]:
model[7].gradient

1014×84 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ⋮                        ⋮              ⋱                 ⋮              
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

In [195]:
model[1] = Constant(x4dim[:,:,:,3])
model[12] = Constant(reshape(yhot[:,3],1,10))

const [0 0 … 0 0]

In [141]:
model[2].output

3×3×1×6 Array{Float64, 4}:
[:, :, 1, 1] =
 -0.177736    -0.0156044   0.0873866
 -0.00385951  -0.175474   -0.132512
  0.00135291  -0.0312976   0.0570216

[:, :, 1, 2] =
 -0.300797   0.271856    0.169672
  0.10082   -0.0319858  -0.260928
 -0.124501   0.230481   -0.0216921

[:, :, 1, 3] =
  0.2664      0.125745  -0.154283
 -0.0298813  -0.130068   0.2614
 -0.169113   -0.293947   0.170629

[:, :, 1, 4] =
  0.264035  0.101186   0.192357
 -0.134682  0.152155   0.0655297
  0.244346  0.171571  -0.215438

[:, :, 1, 5] =
 -0.265627    0.251423    -0.240172
  0.0181901   0.00366457   0.179892
  0.160627   -0.173334    -0.259599

[:, :, 1, 6] =
 0.170287      0.0164562   0.129692
 0.0605988    -0.240143   -0.22663
 0.000735739   0.307209    0.284612

In [5]:
x4dim = reshape(train_data.features, 28, 28, 1, :) # insert trivial channel dim
yhot  = onehotmatrix(train_data.targets, 0:9)

10×60000 Matrix{Int64}:
 0  1  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  1  0  1  0  0  0  0     0  0  0  0  0  0  1  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0  0  0  0     0  0  0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  1  0  0  1  0  1     0  0  0  0  0  0  0  0  1  0  0  0
 0  0  1  0  0  0  0  0  0  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  0  0  0  0  0  0  0  0  0  0  1  0  …  0  0  0  0  0  1  0  0  0  1  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  1  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  1  0  0  0  0  0  1  0  0  0  1
 0  0  0  0  1  0  0  0  0  0  0  0  0     0  0  1  0  1  0  0  0  0  0  0  0

In [45]:
yhot[:,1]

10-element Vector{Int64}:
 0
 0
 0
 0
 0
 1
 0
 0
 0
 0

In [46]:
settings = (;
eta = 1e-2,
epochs = 3,
batchsize = 100,
)

(eta = 0.01, epochs = 3, batchsize = 100)

In [53]:
train_model(x4dim, yhot, settings.batchsize, settings.eta)

(28, 28, 1, 1)(3, 3, 1, 6)(1014, 84)(84, 10)(1, 10)

MethodError: MethodError: no method matching ndims(::Type{Nothing})

Closest candidates are:
  ndims(!Matched::Type{Union{}}, Any...)
   @ Base abstractarray.jl:276
  ndims(!Matched::Type{<:Number})
   @ Base number.jl:86
  ndims(!Matched::Type{<:Ref})
   @ Base refpointer.jl:96
  ...


In [7]:
for epoch in 1:settings.epochs
    @time for (x,y) in loader(train_data, batchsize=settings.batchsize)
        grads = Flux.gradient(model -> Flux.logitcrossentropy(model(x), y), net)
        sizeof(grads)
        Flux.update!(opt_state, net, grads[1])
    end
    
    loss, acc, _ = loss_and_accuracy(net, train_data)
    test_loss, test_acc, _ = loss_and_accuracy(net, test_data)
    @info epoch acc test_acc
    nt = (; epoch, loss, acc, test_loss, test_acc) 
    push!(train_log, nt)
end

MethodError: MethodError: no method matching loader(::MNIST; batchsize::Int64)

Closest candidates are:
  loader(!Matched::Int64) got unsupported keyword argument "batchsize"
   @ Main d:\Projects\CNNLibrary\src\load_data.jl:22
  loader() got unsupported keyword argument "batchsize"
   @ Main d:\Projects\CNNLibrary\src\load_data.jl:22
